Initial setup of log server
PatternPal/PatternPal pull request #156
Opened 2023-03-27 08:00 UTC by JustNireon

Server setup for logging server 
TODO:

- [x] GRPC log function
- [x] Setup database management
- [x] Dockerize for easy set-up

2023-03-30 12:19 UTC, JustNireon commented
Installation for logging server (will document better later)

Requirements:
- Visual Studio 2022*
- Docker for Windows

1. Run Docker-compose (This will launch the database & server) through visual studio
2. Open a terminal and run `dotnet tool install --global dotnet-ef`
3. Run `dotnet ef database update`
4. Server should be up and running correctly

2023-03-30 12:25 UTC, KnapSac commented on PatternPal/PatternPal.Extension.Protos/PatternPal.Extension.Protos.csproj
@JustNireon This project shouldn't have any dependencies. The only reason it exists is due to some bugs with code generation of both WCF and gRPC in one project.

Any protocol buffer definitions which you want to use from the extension, you need to add here. If you want to use them in the backend, add them to `PatternPal.Core`.

`PatternPal` is the background server, and you should only use gRPc to talk to it, you shouldn't add a dependency on it.

2023-03-30 13:05 UTC, JustNireon commented on PatternPal/PatternPal.Extension.Protos/PatternPal.Extension.Protos.csproj
Oop happened on accident

2023-04-03 20:00 UTC, KnapSac requested changes
I've left some comments with requests for changes. A few of the comments are nits, you can fix them if you want, but I wouldn't block merging over them.

Can you also add some documentation on how to build & run the container, with and without VS (so from the commandline)? The steps you outline in one of your comments work, but this is not very futureproof, as no one wants to look through PRs to find the magic incantation to make stuff work. Maybe you can create a script in the `Tools/` directory which does all the work, that makes it a lot easier for others to use the docker container.

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Dockerfile
> +FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
Why don't you use `net7.0` here? That's the version we use in the rest of the project, and I'd prefer to keep that version one and the same throughout the project, with exception of the VS extension of course (as it requires .NET Framework).

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Dockerfile.original
Is this file used? Or was this just the file included by the template?

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/PatternPal.LoggingServer.csproj
> +    <TargetFramework>net6.0</TargetFramework>
Same question as earlier, why not use `net7.0` here?

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/PatternPal.LoggingServer.csproj
> +    <None Remove="DAL\**" />
What's up with this? These files no longer exist in the repo right? If so, this should be removed.

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Program.cs
> +
This is more of a nit, and I wouldn't block merging over this, but these empty lines are unnecessary. There are more occurrences of this throughout the PR.

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Protos/log.proto
> +    CUSTOM = 22;
Enum values in Protocol Buffers should have a prefix, as they're in the global scope, see the [documentation](https://protobuf.dev/programming-guides/proto3/#enum).

The `0` value also shouldn't be used.

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Protos/log.proto
> +service Log {
In the other gRPC services, I've used the convention of postfixing the service with `Service`, I'd like to stick to that convention.

It's probably also a good idea to be clear about the difference between the logging service which is exposed by the background process, and the logging service which runs remotely and collects the data. Perhaps this should be `LogCollectorService`, and the service exposed by the background process could simply be `LogService`.

```suggestion
service LogCollectorService {
```

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Protos/log.proto
> +  rpc Log (LogRequest) returns (LogReply);
In the other protos I use the convention of postfixing a request with `Request`, and a response/reply with `Response`.

```suggestion
  rpc Log (LogRequest) returns (LogResponse);
```

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Protos/log.proto
I think that we should keep all the protos in the same directory (`Protos/` in the root of the repository), as these files define important contracts, they should be easily findable. Also, because they're used by atleast 2 projects each, it doesn't really make sense to put them inside one project.

Nit: The indentation is inconsistent in this file, I use an indentation of 4 spaces in the other protos. The exact value doesn't really matter, but consistency does.

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/Protos/log.proto
> +  string subjectID = 1;
Field names should use `lower_snake_case`, see the [documentation](https://protobuf.dev/programming-guides/style/#message-field-names).

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/PatternPal.LoggingServer/libman.json
What is this file for?

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/docker-compose.dcproj
I don't like having these files directly in the `PatternPal/` folder, as VS will also put the build output in that folder, leading to a lot of clutter. I think we should move them to a dedicated folder, or is that not possible for some reason?

2023-04-03 20:00 UTC, KnapSac commented on PatternPal/docker-compose.dcproj
> +    <None Remove="NewFolder\**" />
This is no longer needed right? If the file isn't included in the repo, it shouldn't be mentioned here. If it still exists in your local checkout, you can safely delete it.

2023-04-13 11:00 UTC, ovda96 commented
@JustNireon Is this ready for merging?

2023-04-13 11:50 UTC, merged