Refactor/110/feedback changes testcases
PatternPal/PatternPal pull request #202
Opened 2023-05-01 14:29 UTC by rutgervincken

2023-05-01 14:29 UTC, rutgervincken commented
Linde doet dit morgen

2023-05-02 09:13 UTC, LvanWerven commented
Matteo gaat deze nakijken

2023-05-02 10:20 UTC, ViciousDoormat requested changes

2023-05-02 10:20 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/New_TestCasesRecognizers/Strategy/StrategyTestCase12.cs
>  namespace PatternPal.Tests.TestClasses.Strategy
This implementation does not correspond to the explanation above.
The concrete strategy does not implement the interface anymore, yet in the explanation, there is a check at "is an implementation of the strategy interface".
Please also check that the other implementations do correspond with their explanation. Just to be sure.

2023-05-02 11:48 UTC, rutgervincken commented
doe accepteren

2023-05-02 13:13 UTC, JustNireon requested changes
LGTM

2023-05-02 13:44 UTC, JustNireon approved these changes

2023-05-02 13:45 UTC, merged