Refactor/151/implement param of method check.check()
PatternPal/PatternPal pull request #203
Opened 2023-05-02 08:40 UTC by DanielvanDamme

Implemented the parametercheck and added the call to that parametercheck in the methodcheck and constructorcheck. All return paths have a unit test in the test project under parameterchecktest.

2023-05-02 14:20 UTC, LvanWerven requested changes
Ik heb alleen even gekeken naar de feedbackMessages, en dit heb ik snel gedaan dus check zelf ook nog even dat er geen emtpy FeedbackMessages meer zijn maar die altijd volgens het format zoals in de comment beschreven staat staan.

2023-05-02 14:20 UTC, LvanWerven commented on PatternPal/PatternPal.Core/Checks/ParameterCheck.cs
> +            FeedbackMessage = String.Empty,
Maak van de FeedbackMessage een message van het volgende format: $"Found parameters for following node: {node}."

2023-05-02 14:49 UTC, ViciousDoormat requested changes

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Core/Checks/ParameterCheck.cs
> +/// <summary>
Use <see .../> here to refer to the list of typechecks used. Look at other Checks for example comments

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Core/Checks/ParameterCheck.cs
> +    // The types the parameters should have.
Unclear comment. I would say something as: there should be parameters present with the types in this list of typechecks

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Core/Checks/ParameterCheck.cs
> +        // Retrieve the parameters the method has to compare to list of TypeChecks and convert to
It is not necessarily a method. It can be a constructor as well. So use something like entity instead to refer to the node

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Core/Checks/ParameterCheck.cs
> +                    case NodeCheckResult nodeCheckResult:
Currently the check for a nodecheckresult fails when one of its leafs is incorrect. It should be the opposite. It should succeed when at least 1 is correct, and thus fail when all are incorrect.

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/Checks/ParameterCheckTests.cs
> +        IMethod stringNode =
There is a function for this you could call in Relations

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/Utils/EntityNodeUtils.cs
> +                                 public class IntTest
This name is somewhat confusing when you refer to it. You refer to it as an Int node, which gives the impression the parameter has the type of int. But it is a class.

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/Checks/ParameterCheckTests.cs
> +    public Task Parameter_Check_Method_Wrong_Type()
Make clear why this test fails

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/Checks/ParameterCheckTests.cs
> +    // TODO add method in test file without parameters.
Is this TODO still relevant?

2023-05-02 14:49 UTC, ViciousDoormat commented on PatternPal/PatternPal.Tests/Checks/ParameterCheckTests.cs
> +    public Task Parameter_Less_Checks_Than_Parameters()
It is not clear from this name what the test checks.
If I understand correctly, you check a method with a check that contains more typechecks than there are parameters in the method.
So Something like Less_Parameters_Than_TypeChecks

2023-05-03 17:50 UTC, ViciousDoormat approved these changes

2023-05-03 17:56 UTC, merged