log: Add comments to entire logging server
PatternPal/PatternPal pull request #204
Opened 2023-05-02 08:56 UTC by JustNireon

2023-05-03 12:44 UTC, ovda96 requested changes
I've added some things I feel are lacking in the current commenting; see specific files for more details!

2023-05-03 12:44 UTC, ovda96 commented on PatternPal/PatternPal.LoggingServer/Models/ProgSnap2.cs
For the entire thing: all are not xml-comments, right?

2023-05-03 12:44 UTC, ovda96 commented on PatternPal/PatternPal.LoggingServer/Data/EventRepository.cs
> +        /// <returns></returns>
For all subsequent comments: returns should include return type/description.

2023-05-15 08:13 UTC, WingToh approved these changes
Good.

2023-05-16 08:26 UTC, WingToh approved these changes

2023-05-16 09:21 UTC, merged