Feat/165/compile error log
PatternPal/PatternPal pull request #207
Opened 2023-05-03 10:28 UTC by WingToh

Test the following:
-Open a new project/solution
-Close a new project/solution
-Try to compile with a compile error

2023-05-03 14:06 UTC, JustNireon reviewed
LGTM up till the last commit since i've commited this myself. This should be reviewed by someone else.

2023-05-04 07:24 UTC, ovda96 requested changes

2023-05-04 07:24 UTC, ovda96 commented on PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
> +        #region MyRegion
I don't think that you want this as the region title, right?

2023-05-04 07:24 UTC, ovda96 commented on PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
> +            string nametest = _dte.Solution.FullName;
According to naming convention: nameTest

2023-05-04 10:20 UTC, ovda96 commented
@WingToh Please, also adapt the PR-name to reflect the commit conventions.

2023-05-04 13:00 UTC, ovda96 requested changes

2023-05-04 13:00 UTC, ovda96 commented on PatternPal/PatternPal.Extension/Commands/SubscribeEvents.cs
> +            _dte.Events.DebuggerEvents.OnEnterDesignMode += OnRunProgram; //Not triggering...
Maybe add `TODO` before the comment?

2023-05-04 13:05 UTC, ovda96 approved these changes

2023-05-04 13:13 UTC, merged